# encoding: UTF-8

# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).

# This file was created automatically using rake export:seeds_format

Movie.create("category_id"=>1, "description"=>"This tragicomedy is a self-ironic portrait of a young man who drops out of university and ends up wandering the streets of the city he lives in: Berlin. The film deals with the desire to participate in life and the difficulty to find one's place. Black and white, tragic and funny, Oh Boy! is a winning debut from director Jan Ole Gerster.", "image_url"=>"http://ecx.images-amazon.com/images/G/01/lovefilm/de/images/products/324347/packshot._UX140_CR0,0,140,200_V1362778663_Lovefilmde324347_.jpg", "title"=>"Oh Boy", "year"=>2013)

Movie.create("category_id"=>1, "description"=>"Steven Spielberg's Academy Award-winning political biopic stars Daniel Day-Lewis as America's 16th president Abraham Lincoln. The film focuses on the last few months of Lincoln's life, which not only saw the ending of slavery despite dogged opposition from many inside Lincoln's own cabinet, but also the Union victory in the American Civil War. The supporting cast includes Sally Field as Lincoln's wife Mary, Joseph Gordon-Levitt as Lincoln's son Robert and Tommy Lee Jones as Radical Republican Congressional leader Thaddeus Stevens. Daniel Day-Lewis won the Academy Award, a Golden Globe and a BAFTA for Best Actor for his performance.", "image_url"=>"http://ecx.images-amazon.com/images/G/01/lovefilm/gb/images/products/195313/packshot._UX140_CR0,0,140,200_V1375293896_Lovefilmgb195313_.jpg", "title"=>"Lincoln", "year"=>2012)

Movie.create("category_id"=>1, "description"=>"Mysterious and mythical motorcycle racer, Luke, (Ryan Gosling) desperately tries to connect with a former lover, Romina, (Eva Mendes) who secretly gave birth to the stunt rider’s son. In an attempt to provide for his new family, Luke commits a series of bank robberies aided by his superior riding ability. The stakes rise as Luke is put on a collision course with an ambitious police officer, Avery Cross, (Bradley Cooper) looking to quickly move up the ranks in a police department riddled with corruption.", "image_url"=>"http://ecx.images-amazon.com/images/G/01/lovefilm/gb/images/products/209804/packshot._UX140_CR0,0,140,200_V1372102452_Lovefilmgb209804_.jpg", "title"=>"The Place Beyond the Pines", "year"=>2012)

Movie.create("category_id"=>0, "description"=>"In the futurist action thriller Looper, time travel will be invented - but it will be illegal and only available on the black market. When the mob wants to get rid of someone, they will send their target 30 years into the past, where a looper - a hired gun, like Joe - is waiting to mop up. Joe is getting rich and life is good... until the day the mob decides to \"close the loop,\" sending back Joe's future self for assassination.", "image_url"=>"http://ecx.images-amazon.com/images/G/01/lovefilm/gb/images/products/198125/packshot._UX500_PJStripe-HD-Only-500px,TopLeft,0,0_UX140_CR0,0,140,200_V1356722311_Lovefilmgb198125_.jpg", "title"=>"Looper", "year"=>2012)

Movie.create("category_id"=>2, "description"=>"The story of an Indian boy named Pi, a zookeeper's son who finds himself in the company of a hyena, zebra, orangutan, and a Bengal tiger after a shipwreck sets them adrift in the Pacific Ocean.", "image_url"=>"http://ecx.images-amazon.com/images/G/01/lovefilm/gb/images/products/188538/packshot._UX140_CR0,0,140,200_V1376417045_Lovefilmgb188538_.jpg", "title"=>"Life of Pi", "year"=>2012)

Movie.create("category_id"=>3, "description"=>"Heart-warming Pixar animated tale about a robot who accidentally discovers the way to save planet Earth. 700 years after humanity has left Earth, WALL-E (Waste Allocation Load Lifter Earth-Class) fills his days collecting rubbish, and anything else that takes his fancy, trying to fend off the boredom of his lot. But unknowingly, the tiny tube-eyed robot has discovered a secret that could make the once beautiful planet habitable again, enabling humankind to return. One day, Eve, a search robot, lands on Earth in a cloud of dust, and WALL-E is smitten. When she realizes the importance of his find, she sets out to tell the remaining humans, eager to let them know the planet can be saved. But WALL-E, after centuries of being alone, can't bear to see her go, and hitches a ride through the cosmos on an adventure his memory banks will never forget.", "image_url"=>"http://ecx.images-amazon.com/images/G/01/lovefilm/gb/images/products/216504/packshot._UX500_PJStripe-HD-Only-500px,TopLeft,0,0_UX140_CR0,0,140,200_V1366222750_Lovefilmgb216504_.jpg", "title"=>"WALL-E", "year"=>2008)

Movie.create("category_id"=>0, "description"=>"Mystery crime drama starring Tom Cruise and Rosamund Pike. Adapted from a novel in Lee Child's best-selling crime series, the film sees Cruise in the title role as an ex-military policeman turned vigilante drifter who is called in to investigate after an expert sniper takes the lives of five random victims. When the authorities pull in former army sniper, James Barr (Joseph Sikora), they are certain they have the perpetrator, but Barr believes he's been set up and asks that Jack Reacher (Cruise) be assigned to the case. At first, Reacher is weary of Barr but after some thorough investigation he is led to believe there is an unseen force pulling the strings of the investigation and he's determined to get to the truth.", "image_url"=>"http://ecx.images-amazon.com/images/G/01/lovefilm/gb/images/products/193566/packshot._UX140_CR0,0,140,200_V1364926515_Lovefilmgb193566_.jpg", "title"=>"Jack Reacher", "year"=>2012)

Movie.create("category_id"=>3, "description"=>"Romantic comedy starring Reese Witherspoon, Owen Wilson and Paul Rudd. Former athlete Lisa (Witherspoon) meets troubled business executive George (Rudd) at a bad time. While Lisa is facing a difficult transition in her life, feeling past her athletic prime and questioning her current relationship with egotistical baseball player Manny (Wilson), George is facing the prospect of financial ruin as his father's company is subject to a federal investigation for shady dealing. But can romance blossom despite the odds? And how do you know who is 'the one'? Jack Nicholson co-stars as George's father, Charles.", "image_url"=>"http://ecx.images-amazon.com/images/G/01/lovefilm/gb/images/products/165559/packshot._UX140_CR0,0,140,200_V1349719668_Lovefilmgb165559_.jpg", "title"=>"How Do You Know", "year"=>2010)

Movie.create("category_id"=>4, "description"=>"A U.N. employee is racing against time and fate, as he travels the world trying to stop the outbreak of a deadly Zombie pandemic.", "image_url"=>"http://ecx.images-amazon.com/images/G/01/lovefilm/gb/images/products/177289/packshot._UX140_CR0,0,140,200_V1355167347_Lovefilmgb177289_.jpg", "title"=>"World War Z", "year"=>2012)

Movie.create("category_id"=>4, "description"=>"Director Sam Raimi's first film has achieved legendary status since its 1982 release, and for good reason. Though perhaps not as widely seen as its two sequels, EVIL DEAD 2 and ARMY OF DARKNESS, THE EVIL DEAD is arguably the best of the three. It is the story of five college-age friends who travel to a cabin in rural Tennessee where the stumble upon the Book of the Dead, an ancient tome bound in human flesh and inked in blood. After unwittingly awakening the unspeakable terror told of in the book, each of the friends is transformed into the evil dead, one by one, except for Ash (Bruce Campbell). So Ash is left with no other way to survive than to dismember the living corpses of his sister, girlfriend, and two of his friends. Shot on a shoestring budget, the film boasts some impressive camera work and extremely over the top gore effects as well as a sense of humor much more subtle than the tongue-in-cheek aesthetic of the two sequels.", "image_url"=>"http://ecx.images-amazon.com/images/G/01/lovefilm/gb/images/products/149992/packshot._UX140_CR0,0,140,200_V1349730417_Lovefilmgb149992_.jpg", "title"=>"The Evil Dead", "year"=>1982)

Movie.create("category_id"=>2, "description"=>"After the crew of the Enterprise find an unstoppable force of terror from within their own organization, Captain Kirk leads a manhunt to a war-zone world to capture a one man weapon of mass destruction.", "image_url"=>"http://ecx.images-amazon.com/images/G/01/lovefilm/gb/images/products/195382/packshot._UX140_CR0,0,140,200_V1375120946_Lovefilmgb195382_.jpg", "title"=>"Star Trek Into Darkness", "year"=>2013)

Movie.create("category_id"=>2, "description"=>"Tumble down the rabbit hole with Alice for a fantastical adventure from Walt Disney Pictures and Tim Burton. Inviting and magical, Alice In Wonderland is an imaginative new twist on one of the most beloved stories of all time. Alice (Mia Wasikowska), now 19 years old returns to the whimsical world she first entered as a child and embarks on a journey to discover her true destiny. This Wonderland is a world beyond your imagination and unlike anything you've seen before. The extraordinary characters you've loved come to life richer and more colorful than ever. There's a Mad Hatter (Johnny Depp), the White Queen (Anne Hathaway), the Red Queen (Helena Bonham Carter), the White Rabbit (Michael Sheen) and more. A triumphant cinematic experience - Alice in Wonderland is an incredible feast for your eyes, ears and heart that will captivate audiences for all sizes.", "image_url"=>"http://ecx.images-amazon.com/images/G/01/lovefilm/gb/images/products/216349/packshot._UX500_PJStripe-HD-Only-500px,TopLeft,0,0_UX140_CR0,0,140,200_V1375725880_Lovefilmgb216349_.jpg", "title"=>"Alice in Wonderland", "year"=>2010)

Movie.create("category_id"=>3, "description"=>"When Blu, a domesticated, nerdy macaw from small-town Minnesota, meets the fiercely independent Jewel, he takes off on an adventure to Rio de Janeiro with this bird of his dreams.", "image_url"=>"http://ecx.images-amazon.com/images/G/01/lovefilm/gb/images/products/211378/packshot._UX140_CR0,0,140,200_V1372188893_Lovefilmgb211378_.jpg", "title"=>"Rio", "year"=>2011)

Movie.create("category_id"=>0, "description"=>"A chronicle of the decade-long hunt for al-Qaeda terrorist leader Osama bin Laden after the September 2001 attacks, and his death at the hands of the Navy S.E.A.L. Team 6 in May 2011.", "image_url"=>"http://ecx.images-amazon.com/images/G/01/lovefilm/gb/images/products/195533/packshot._UX140_CR0,0,140,200_V1375985037_Lovefilmgb195533_.jpg", "title"=>"Zero Dark Thirty", "year"=>2012)

Movie.create("category_id"=>1, "description"=>"In 19th-century France, Jean Valjean, who for decades has been hunted by the ruthless policeman Javert after he breaks parole, agrees to care for factory worker Fantine's daughter, Cosette. The fateful decision changes their lives forever.", "image_url"=>"http://ecx.images-amazon.com/images/G/01/lovefilm/gb/images/products/194105/packshot._UX140_CR0,0,140,200_V1372786498_Lovefilmgb194105_.jpg", "title"=>"Les Misérables", "year"=>2012)

Movie.create("category_id"=>3, "description"=>"In THE SWEETEST THING, three single women, Christina, Courtney and Jane, regularly have a good time in the city's nightclub. Then one night Christina meets her perfect partner but discovers too late that he's left town. Now she and Courtney are off on the road to find him.", "image_url"=>"http://ecx.images-amazon.com/images/G/01/lovefilm/gb/images/products/161369/packshot._UX500_PJStripe-HD-Only-500px,TopLeft,0,0_UX140_CR0,0,140,200_V1349723606_Lovefilmgb161369_.jpg", "title"=>"The Sweetest Thing", "year"=>2002)

Movie.create("category_id"=>1, "description"=>"When we first meet New York hedge-fund magnate Robert Miller (Richard Gere), he appears the very portrait of success in American business and family life. However, behind the gilded walls of his mansion, Miller is in over his head, desperately trying to conceal an affair with artist Julie Cote (Laetitia Casta) whilst racing to complete the sale of his empire before his fraudulent dealings can be revealed. When a tragic accident complicates things further, attracting the unwanted attention of tenacious NYPD detective Michael Bryer (Roth), Miller finds himself battling not just for his reputation but also his life. As the net tightens around him, Miller realizes that the suspicions of not just the police but also his loyal wife (Susan Sarandon) and heir-apparent (Brit Marling) have been aroused. With time running out, can Miller find a way out without destroying his own life and those around him?", "image_url"=>"http://ecx.images-amazon.com/images/G/01/lovefilm/gb/images/products/177166/packshot._UX140_CR0,0,140,200_V1373477725_Lovefilmgb177166_.jpg", "title"=>"Arbitrage", "year"=>2012)

Movie.create("category_id"=>0, "description"=>"Acclaimed filmmaker Christopher Nolan directs an international cast in an original sci-fi actioner that travels around the globe and into the intimate and infinite world of dreams. Dom Cobb (Leonardo DiCaprio) is a skilled thief, the absolute best in the dangerous art of extraction, stealing valuable secrets from deep within the subconscious during the dream state, when the mind is at its most vulnerable. Cobb’s rare ability has made him a coveted player in this treacherous new world of corporate espionage, but it has also made him an international fugitive and cost him everything he has ever loved. Now Cobb is being offered a chance at redemption. One last job could give him his life back but only if he can accomplish the impossible–inception. Instead of the perfect heist, Cobb and his team of specialists have to pull off the reverse: their task is not to steal an idea but to plant one. If they succeed, it could be the perfect crime. But no amount of careful planning or expertise can prepare the team for the dangerous enemy that seems to predict their every move. An enemy that only Cobb could have seen coming.", "image_url"=>"http://ecx.images-amazon.com/images/G/01/lovefilm/gb/images/products/160282/packshot._UX140_CR0,0,140,200_V1349252448_Lovefilmgb160282_.jpg", "title"=>"Inception", "year"=>2010)

Movie.create("category_id"=>4, "description"=>"Supernatural horror in which a suburban family are terrified by mysterious spirits. Like many loving parents, Lacy and Daniel Barrett (Keri Russell and Josh Hamilton) have retreated to quiet suburban streets to raise their children. They are more or less content until a series of strange occurrences at night unsettle them. Their son Jesse (Dakota Goyo) is particularly disturbed by events which include a confluence of migrating birds smashing into the house. With the police and other authority figures apparently unable to help, Lacy and Daniel are gradually drawn to a supernatural interpretation of events. Unfortunately, as an expert on the paranormal (J.K. Simmons) informs them, there may not be much they can do to resist the spirits. Even worse, when Lacy and Daniel begin to feel themselves losing control of their own actions, it raises the possibility that the spirits aren't merely within the house; they may be within them...", "image_url"=>"http://ecx.images-amazon.com/images/G/01/lovefilm/gb/images/products/201768/packshot._UX140_CR0,0,140,200_V1372786407_Lovefilmgb201768_.jpg", "title"=>"Dark Skies", "year"=>2013)

Movie.create("category_id"=>0, "description"=>"With the help of his mentor, a slave-turned-bounty hunter sets out to rescue his wife from a brutal Mississippi plantation owner.", "image_url"=>"http://ecx.images-amazon.com/images/G/01/lovefilm/gb/images/products/177290/packshot._UX140_CR0,0,140,200_V1371058543_Lovefilmgb177290_.jpg", "title"=>"Django Unchained", "year"=>2013)

